#!/usr/bin/env bash

uvx modal volume create compression &> /dev/null
uvx modal volume put compression $1 --force
uvx modal run compression.py::compress --file-name="$1"
uvx modal volume get compression "$1.nc" --force
