#!/usr/bin/env bash

# Clone llama.cpp
git clone 'https://github.com/ggml-org/llama.cpp'
cd llama.cpp

# Create and activate virtual environment
python3 -m venv venv
source venv/bin/activate

# Install llama.cpp dependencies
pip install -r requirements.txt

pip install huggingface_hub[cli]

huggingface-cli download HuggingFaceTB/SmolLM2-135M-Instruct \
  --local-dir SmolLM2-135M-Instruct \
  --local-dir-use-symlinks False

python convert_hf_to_gguf.py SmolLM2-135M-Instruct \
  --outfile smollm2-135m-f32.gguf \
  --outtype f32

mv smollm2-135m-f32.gguf ../smollm2-135m-f32.gguf
